['MARIA LUISA CARDOSO|Alameda - Veneza|29|30|nan|Viúvo|',
 'VITÓRIA GIZELE PEREIRA DA SILVA |Alameda - Veneza|40|2|nan|Solteiro|',
 'SILAS DAVID GUIMARÃES |Jardim Copacabana|10|18|nan|Solteiro|',
 'MARIO FERNANDO SALES|Jardim Copacabana|14|18|nan|Solteiro|',
 'HUGO GABRIEL|Jardim Copacabana 2|20|14|nan|Solteiro|',
 'HIAGO JADIR ANDRADE  DOS SANTOS|Jardim Copacabana 2|21|11|nan|Solteiro|',
 'EMMILY KATLY MARTINS ALVES|Jardim Copacabana|33|17|nan|Solteiro|',
 'JÉSSICA YUSCKA MATOS DE VASCONCELOS |Jardim Copacabana|42|18|nan|Solteiro|',
 'EFRAIM PEDRO|Jardim Copacabana|47|17|nan|Solteiro|',
 'MARIA LUIZA SANTOS SILVA |Jardim Copacabana|48|17|nan|Solteiro|',
 'JOSÉ CAUÃ SALES DE AZEVEDO |Jardim Copacabana|51|14|nan|Solteiro|',
 'SAULO DE TACIO GUIMARÃES COSTA|Jardim Copacabana|53|16|nan|Solteiro|',
 'JULIA HAYANNE DA SILVA VIEIRA |Jardim Copacabana|56|17|nan|Solteiro|',
 'MATHEUS GUEDES|Jardim Copacabana|75|17|nan|Solteiro|',
 'GUSTAVO RAMOS|Jardim Copacabana|8|25|nan|Solteiro|',
 'ARIELLY SABRINNA|Nova Divinéia 2|12|15|nan|Solteiro|',
 'EDUARDO FERREIRA DE ARAÚJO|Nova Divinéia 2|17|16|nan|Solteiro|',
 'ENZO FERREIRA DE ARAÚJO|Nova Divinéia 2|18|12|nan|Solteiro|',
 'ELAINE STEFANY DA SILVA|Nova Divinéia|59|14|nan|Solteiro|',
 'ELIANDRA STEFANY DA SILVA|Nova Divinéia|63|12|nan|Solteiro|',
 'MIKAELLY|Piedade|106|17|nan|Solteiro|',
 'ANA BEATRIZ FERREIRA |Piedade|107|13|nan|Solteiro|',
 'MARIELLY SANTOS DE SOUZA|Piedade|117|18|nan|Solteiro|',
 'WILLAMIS CARLOS NASCIMENTO |Piedade|118|29|nan|Solteiro|',
 'WILKER FRANKLIN G. DO NASCIMENTO |Piedade|133|19|nan|Solteiro|',
 'ISAAC SANTOS DE SOUZA|Piedade|135|13|nan|Solteiro|',
 'LETÍCIA DE BARROS ARAÚJO |Piedade|148|22|nan|Solteiro|',
 'JAMILLY XAVIER DA SILVA|Piedade|166|15|nan|Solteiro|',
 'MARINA ANTÔNIA CONCEIÇÃO|Piedade|17|30|nan|Viúvo|',
 'KELTON DA SILVA PEREIRA|Piedade|187|20|nan|Solteiro|',
 'LUDMILLA SUELLEN|Piedade|199|14|nan|Solteiro|',
 'WANGLEIS RAMOS DE LIMA JR|Piedade|203|29|nan|Solteiro|',
 'EDUARDO HENRIQUE VELOSO DO NASCIMENTO|Piedade|215|17|nan|Solteiro|',
 'ISAQUE FERREIRA GOMES|Piedade|218|12|nan|Solteiro|',
 'MUNIQUE NAYARA |Piedade|40|33|nan|Viúvo|',
 'ADRIANO MIRANDA EUZEDIO|Piedade|52|23|nan|Solteiro|',
 'MARLON GABRIEL DE M. SANTOS |Piedade|68|18|nan|Solteiro|',
 'THAISSA DE LIMA VICENTE |Piedade|69|19|nan|Solteiro|',
 'KETHYENE FERREIRA|Piedade|70|20|nan|Solteiro|',
 'JONATAS SILVA DE OLIVEIRA |Veneza 4|12|21|nan|Solteiro|',
 'ÁLIFE NASCIMENTO DE ALBUQUERQUE |Veneza 4|14|18|nan|Solteiro|',
 'REBECA JÚLIA |Veneza 4|18|16|nan|Solteiro|',
 'JOÃO VICTOR|Nova Divinéia 2|98|22|nan|Solteiro|',
 'ALEXANDRE JOSÉ|Jardim Copacabana|98|25|nan|Solteiro|',
 'KIMBERLLY MARIA|Jardim Copacabana|99|24|nan|Solteiro|']
