name: CI-CD v2.00
on:
  push:
    branches:
      - v2.00
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.2
      - name: Atualizar arquivos sensíveis
        shell: bash
        run: |
          bash -c 'replace_pw () { pw="$1"; while read line; do var=$(echo $line | cut -d= -f1); value=$(echo $line | cut -d= -f2); if [ "$value" == "{{DJANGO_SUPERUSER_PASSWORD}}" ]; then echo "$var=$pw"; else echo "$var=$value"; fi; done }; cat ./Spacefile | replace_pw '\''${{ secrets.DJANGO_SUPERUSER_PASSWORD }}'\' > junk.$$; mv junk.$$ ./Spacefile
      - name: Conexão com o DetaSpace
        uses: neobrains/space-pipe@v0.5
        with:
          access_token: ${{ secrets.DETA_ACCESS_TOKEN }}
          project_id: ${{ secrets.DETA_ID_PROJECT }}
          space_push: true
      - name: Executar o deploy
        run: echo "Deploy executado"
        
