name: CI-CD v2.00
on:
  push:
    branches:
      - v2.00
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.2
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.DJANGO_SUPERUSER_PASSWORD }}"
      - name: Atualizar arquivos sensíveis (DJANGO_SUPERUSER_PASSWORD)
        shell: bash
        run: |
          sed -i "s/{{DJANGO_SUPERUSER_PASSWORD}}/${{ secrets.DJANGO_SUPERUSER_PASSWORD }}/g" ./Spacefile
      - name: Atualizar arquivos sensíveis (DJANGO_SUPERUSER)
        shell: bash
        run: |
          sed -i "s/{{DJANGO_SUPERUSER}}/${{ secrets.DJANGO_SUPERUSER }}/g" ./Spacefile
      - name: visualizar spacefile
        shell: bash
        run: |
          cat ./Spacefile
      - name: Atualizar arquivos sensíveis (DETA_PROJECT_KEY)
        shell: bash
        run: |
          sed -i "s/{{DETA_PROJECT_KEY}}/${{ secrets.DETA_PROJECT_KEY }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (FIREBASE_URL)
        shell: bash
        run: |
          sed -i "s/{{FIREBASE_URL}}/${{ secrets.FIREBASE_URL }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (DJANGO_SECRET_KEY)
        shell: bash
        run: |
          sed -i "s/{{DJANGO_SECRET_KEY}}/${{ secrets.DJANGO_SECRET_KEY }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (MYSQL_USER)
        shell: bash
        run: |
          sed -i "s/{{MYSQL_USER}}/${{ secrets.MYSQL_USER }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (MYSQL_PASSWORD)
        shell: bash
        run: |
          sed -i "s/{{MYSQL_PASSWORD}}/${{ secrets.MYSQL_PASSWORD }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (MYSQL_HOST)
        shell: bash
        run: |
          sed -i "s/{{MYSQL_HOST}}/${{ secrets.MYSQL_HOST }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (MYSQL_PORT)
        shell: bash
        run: |
          sed -i "s/{{MYSQL_PORT}}/${{ secrets.MYSQL_PORT }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (DETA_SORTEIO)
        shell: bash
        run: |
          sed -i "s/{{DETA_SORTEIO}}/${{ secrets.DETA_SORTEIO }}/g" ./enums/env_deta.py
      - name: Atualizar arquivos sensíveis (DETA_USER)
        shell: bash
        run: |
          sed -i "s/{{DETA_USER}}/${{ secrets.DETA_USER }}/g" ./enums/env_deta.py
      - name: Conexão com o DetaSpace
        uses: neobrains/space-pipe@v0.5
        with:
          access_token: ${{ secrets.DETA_ACCESS_TOKEN }}
          project_id: ${{ secrets.DETA_ID_PROJECT }}
          space_push: true
      - name: Executar o deploy
        run: echo "Deploy executado"
        
